camel:
  component:
    jms:
      connection-factory: cachingConnectionFactory
  rest:
    context-path: /camel
    enable-cors: true
    api-context-path: /v2/api-docs
    api-property.api:
      title: Beer API with metrics
      version: v1

hawtio:
  realm: hawtio
  rolePrincipalClasses: org.eclipse.jetty.jaas.JAASRole
  roles: admin

logging.level:
  io:
    hawt: INFO
    undertow: WARN
  org:
    eclipse:
      jetty: WARN
    springframework: WARN

management:
  endpoints:
    web:
      exposure:
        include: hawtio,jolokia,metrics
  metrics:
    enable:
      root: false
      jvm: true
  server:
    port: 8912

server:
  port: 8080

spring:
  jmx:
    enabled: true
  profiles:
    active: development

springfox:
  documentation:
    swagger:
      v2:
        path: /camel/v2/api-docs

hazelcast:
  map:
    beer-cache: beer-cache
