artemis:
  password: admin
  user: admin
  broker-url: tcp://localhost:61616

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hazelcast
    username: hc_admin
    password: password

hazelcast:
  filestore:
    directory: /home/rphgoossens/Temp/filestores/

logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE